services:
  db:
    build:
      context: ./postgres
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  backend:
    image: backend:transcendence
    container_name: backend
    build: ./backend
    ports:
      - '8000:8000'
    networks:
      - network
    volumes:
      - backend-media:/app/media

  frontend:
    image: frontend:transcendence
    container_name: frontend
    build: ./frontend
    ports:
      - '3000'
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - frontend-data:/app/dist
    networks:
      - network

  nginx:
    image: nginx:transcendence
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - network
    volumes:
      - frontend-data:/usr/share/nginx/html
      - backend-media:/app/media

volumes:
  frontend-data:
  backend-media:
  postgres-data:


networks:
  network:
    driver: bridge
