apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: back-shared-storage
provisioner: kubernetes.io/no-provisioner # 동적 프로비저닝 안 함. 주로 로컬 볼륨에서 사용
volumeBindingMode: WaitForFirstConsumer # pvc가 파드에 의해 실행 될 때까지 바인딩 보류

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: back-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # 여러 파드에서 동시에 읽기, 쓰기 가능
  persistentVolumeReclaimPolicy: Retain  # pvc가 삭제되어도 데이터 보존
  storageClassName: back-shared-storage
  local:
    path: DIR/data/media
  nodeAffinity:  # 특정 노드만 사용 가능
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: back-data
  namespace: app
spec:
  accessModes:
    - ReadWriteMany # backend and frontend
  resources:
    requests:
      storage: 1Gi
  storageClassName: back-shared-storage
