apiVersion: v1
kind: Service
metadata: # 서비스 자체 이름
  name: db
  namespace: app
spec:
  selector: # 연결될 pod 식별
    app: db
  ports:
    - port: 5432 # postgres default port

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - name: "8000" # 포트 쉽게 참조 가능
      port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - name: "443"
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
