apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: front-shared-storage
provisioner: kubernetes.io/no-provisioner # 동적 프로비저닝 안 함. 주로 로컬 볼륨에서 사용
volumeBindingMode: WaitForFirstConsumer # pvc가 파드에 의해 실행 될 때까지 바인딩 보류

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: back-shared-storage
provisioner: kubernetes.io/no-provisioner # 동적 프로비저닝 안 함. 주로 로컬 볼륨에서 사용
volumeBindingMode: WaitForFirstConsumer # pvc가 파드에 의해 실행 될 때까지 바인딩 보류

---

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: front-pv
#spec:
#  capacity:
#    storage: 500Mi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain # pv가 사용되지 않을 때도 데이터 유지, 관리자가 수동으로 삭제 or 다시 사용 가능
#  storageClassName: front-shared-storage
#  local:
#    path: DIR/tmp_data/dist # 로컬 디스크 상의 경로, k8s 노드에도 존재해야 함
#  nodeAffinity: # 특정 노드에서만 사용할 수 있도록 제한
#    required:
#      nodeSelectorTerms: # 노드 선택 조건
#        - matchExpressions: # 노드 레이블에 대한 조건 정의
#            - key: kubernetes.io/hostname # 노드의 호스트 이름을 나타내는 레이블 사용
#              operator: In # 값이 지정된 목록에 포함될 경우 조건 충족
#              values: # pv가 바인딩될 수 있는 노드 목록
#                - docker-desktop

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: back-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: back-shared-storage
  local:
    path: DIR/tmp_data/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop