apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: db-env
  name: db-env
  namespace: app
data:
  POSTGRES_DB: "database"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  PGDATA: "/var/lib/postgresql/data/pgdata" # 마운트된 경로 안의 하위 디렉토리 사용
